{{- if .Values.secret.env.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weathermaps.fullname" . }}-env
type: Opaque
data:
  OPEN_WEATHER_API_KEY: {{ .Values.secret.env.OPEN_WEATHER_API_KEY | b64enc }}
{{- end }}
